# Meta

title:         "Elenore: a modern CSS framework based on Flexbox"
description:   "Elenore is an open source CSS framework based on Flexbox and built with Sass. It's 100% responsive, fully modular, and available for free."

# Build

markdown:      kramdown
permalink:     pretty
url:           https://yellowdi.github.io/Elenore
fontawesome:   https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css
exclude:       ['fontawesome', 'node_modules', 'templates', '.babelrc', 'elenore-docs.sass', 'docker-compose.yml', 'package.json', 'yarn.lock']

# Variables

documentation: "/documentation/overview/start/"
download:      https://github.com/YellowDi/Elenore/archive/1.1.1.zip
github:        https://github.com/YellowDi/Elenore
twitter:       https://twitter.com/YellowDi
version:       1.1.1
vernum:        51
