# Meta

docs_file:     "elenore-docs.min"

# Build

markdown:      kramdown
permalink:     pretty
url:           https://yellowdi.github.io/Elenore
exclude:       ['icons', 'node_modules', 'templates', '.babelrc', 'elenore-docs.sass', 'docker-compose.yml', 'package.json', 'yarn.lock']

# Variables

download:      https://github.com/YellowDi/Elenore/archive/1.3.6.zip
version:       1.3.6
